language: java

jdk:
  - oraclejdk8
# We only need one gradle invocation
install: true

script:
  - ./gradlew assemble check

# Ensures that gradle does not print intermediate task status.
env:
  global:
  - TERM=dumb

